
# Função para definir o grafo do curso de Ciência da Computação
# O grafo é representado por um dicionário, onde cada chave é um id de uma matéria e o valor é um dicionário com os dados da matéria
# A matérias já cursadas recebem o status de 'Cursada' e as matérias que ainda não foram cursadas recebem o status de 'Pendente'
def define_materias_cursadas(materias_cursadas = {}):
    # Colore o grafo inicial com todas matérias com status "Pendente" e define como "Cursadas" caso esteja na lista de "materias_cursadas" dada no input do aluno
    grafoCCO = {
        0: {'Nome': 'Fundamentos de Programação', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 1, "Crédito": 64},
        1: {'Nome': 'Programação Orientada a Objetos', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [0], 'Semestre': 3, "Crédito": 64},
        2: {'Nome': 'Programação Web', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [1], 'Semestre': 4, "Crédito": 64},
        3: {'Nome': 'Engenharia de Software I', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 3, "Crédito": 64},
        4: {'Nome': 'Programação Lógica e Funcional', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [21], 'Semestre': 2, "Crédito": 64},
        5: {'Nome': 'Banco de Dados I', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [14], 'Semestre': 5, "Crédito": 64},
        6: {'Nome': 'Inteligência Artificial', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [22], 'Semestre': 5, "Crédito": 64},
        7: {'Nome': 'Introdução à Computação Visual', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [22, 1], 'Semestre': 5, "Crédito": 64},
        8: {'Nome': 'Redes de Computadores', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [9], 'Semestre': 4, "Crédito": 64},
        9: {'Nome': 'Sistemas Operacionais', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [13, 11], 'Semestre': 3, "Crédito": 64},
        10: {'Nome': 'Arquitetura de Computadores I', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 1, "Crédito": 64},
        11: {'Nome': 'Arquitetura de Computadores II', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [10], 'Semestre': 2, "Crédito": 64},
        12: {'Nome': 'Sistemas Embarcados', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [13, 11], 'Semestre': 4, "Crédito": 64},
        13: {'Nome': 'Algoritmos e Estruturas de Dados I', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [0], 'Semestre': 2, "Crédito": 64},
        14: {'Nome': 'Algoritmos e Estruturas de Dados II', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [13], 'Semestre': 3, "Crédito": 64},
        15: {'Nome': 'Análise e Projeto Orientados a Objeto', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [1], 'Semestre': 5, "Crédito": 64},
        16: {'Nome': 'Projeto e Análise de Algoritmos', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [14, 21, 23], 'Semestre': 4, "Crédito": 64},
        17: {'Nome': 'Teoria da Computação', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [4, 16], 'Semestre': 5, "Crédito": 64},
        18: {'Nome': 'Compiladores', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [17], 'Semestre': 6, "Crédito": 64},
        19: {'Nome': 'Cálculo A', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 1, "Crédito": 64},
        20: {'Nome': 'Cálculo B', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [19], 'Semestre': 2, "Crédito": 64},
        21: {'Nome': 'Matemática Discreta', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 1, "Crédito": 64},
        22: {'Nome': 'Métodos Matemáticos para Análise de Dados', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [19, 13, 21], 'Semestre': 3, "Crédito": 64},
        23: {'Nome': 'Algoritmos em Grafos', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [13], 'Semestre': 3, "Crédito": 64},
        24: {'Nome': 'Modelagem Computacional', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [19], 'Semestre': 2, "Crédito": 64},
        25: {'Nome': 'Cálculo Numérico para Computação', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [19], 'Semestre': 4, "Crédito": 64},
        26: {'Nome': 'Computação e Sociedade', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 7, "Crédito": 64},
        27: {'Nome': 'Interação Humano-Computador', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [2], 'Semestre': 6, "Crédito": 64},
        28: {'Nome': 'Metodologia Científica', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Co-Requisitos': [71], 'Semestre': 7, "Crédito": 64},
        29: {'Nome': 'Projeto Integrado', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 1, "Crédito": 32},
        30: {'Nome': 'Arquitetura de Software', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [3], "Crédito": 64},
        31: {'Nome': 'Padrões de Projeto', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [3, 2], "Crédito": 64},
        32: {'Nome': 'Engenharia de Software Experimental', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [3], "Crédito": 64},
        33: {'Nome': 'Tópicos em DES I', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [3], "Crédito": 64},
        34: {'Nome': 'Tópicos em DES II', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [3], "Crédito": 64},
        35: {'Nome': 'Desenvolvimento de Jogos', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [0], "Crédito": 64},
        36: {'Nome': 'Desenvolvimento para Dispositivos Móveis', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [2], "Crédito": 64},
        37: {'Nome': 'Reutilização de Software', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [38, 1, 31], "Crédito": 64},
        38: {'Nome': 'Engenharia de Software II', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [3], "Crédito": 64},
        39: {'Nome': 'Gerência de projetos de software', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [38], "Crédito": 64},
        40: {'Nome': 'Desenvolvimento de sistemas web', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [3, 5, 2], "Crédito": 64},
        41: {'Nome': 'Maratona de programação I', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [13], "Crédito": 48},
        42: {'Nome': 'Maratona de programação II', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [41], "Crédito": 48},
        43: {'Nome': 'Banco de Dados II', 'Status': 'Pendente', 'Área de atuação': 'Persistência e Análise Dados', 'Tipo': 'Optativa', 'Pré-Requisitos': [5], "Crédito": 64},
        44: {'Nome': 'Introdução à Análise de Dados', 'Status': 'Pendente', 'Área de atuação': 'Persistência e Análise Dados', 'Tipo': 'Optativa', 'Pré-Requisitos': [22], "Crédito": 64},
        45: {'Nome': 'Banco de Dados noSQL', 'Status': 'Pendente', 'Área de atuação': 'Persistência e Análise Dados', 'Tipo': 'Optativa', 'Pré-Requisitos': [5], "Crédito": 64},
        46: {'Nome': 'Tópicos em PAD', 'Status': 'Pendente', 'Área de atuação': 'Persistência e Análise Dados', 'Tipo': 'Optativa', 'Pré-Requisitos': [5, 44], "Crédito": 64},
        47: {'Nome': 'Modelagem Geométrica e Visual', 'Status': 'Pendente', 'Área de atuação': 'Metodologias Computacionais e Otimização', 'Tipo': 'Optativa', 'Pré-Requisitos': [22, 7], "Crédito": 64},
        48: {'Nome': 'Visão Computacional', 'Status': 'Pendente', 'Área de atuação': 'Metodologias Computacionais e Otimização', 'Tipo': 'Optativa', 'Pré-Requisitos': [21, 7], "Crédito": 64},
        49: {'Nome': 'Métodos Exatos', 'Status': 'Pendente', 'Área de atuação': 'Metodologias Computacionais e Otimização', 'Tipo': 'Optativa', 'Pré-Requisitos': [22], "Crédito": 64},
        50: {'Nome': 'Metaheurísticas', 'Status': 'Pendente', 'Área de atuação': 'Metodologias Computacionais e Otimização', 'Tipo': 'Optativa', 'Pré-Requisitos': [22], "Crédito": 64},
        51: {'Nome': 'Tópicos em MCO', 'Status': 'Pendente', 'Área de atuação': 'Metodologias Computacionais e Otimização', 'Tipo': 'Optativa', 'Pré-Requisitos': [22], "Crédito": 64},
        52: {'Nome': 'Auditoria em Segurança de SI', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [8], "Crédito": 64},
        53: {'Nome': 'Computação em Nuvem', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [8], "Crédito": 64},
        54: {'Nome': 'Programação Paralela', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [8], "Crédito": 64},
        55: {'Nome': 'Sistemas Distribuidos', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [8], "Crédito": 64},
        56: {'Nome': 'Tópicos em RSC', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [8], "Crédito": 64},
        57: {'Nome': 'Simulação e Avaliação de Desempenho', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [55], "Crédito": 32},
        58: {'Nome': 'Ciências Humanas e Sociais', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], "Crédito": 48},
        59: {'Nome': 'Psicologia: Relações índividuo-Grupo', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], "Crédito": 48},
        60: {'Nome': 'Ciências, Tecnologias e Organizações', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], "Crédito": 48},
        61: {'Nome': 'Comportamento Organizacional II', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], "Crédito": 32},
        62: {'Nome': 'Gestão de Carreira', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], "Crédito": 32},
        63: {'Nome': 'Psicologia Organizacional e Psicologia do Trabalho', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], "Crédito": 32},
        64: {'Nome': 'Tópicos em AHC', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], "Crédito": 64},
        65: {'Nome': 'Introdução à Administração', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Optativa', 'Pré-Requisitos': [], "Crédito": 32},
        66: {'Nome': 'Empreendedorismo e Inovação', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': 1, "Crédito": 48},
        67: {'Nome': 'Comportamento Organizacional I', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Optativa', 'Pré-Requisitos': [], "Crédito": 48},
        68: {'Nome': 'Gestão e Governança de TI', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Optativa', 'Pré-Requisitos': [65], "Crédito": 64},
        69: {'Nome': 'Economia da Informação', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Optativa', 'Pré-Requisitos': [], "Crédito": 64},
        70: {'Nome': 'Empreendedorismo Técnológico', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Optativa', 'Pré-Requisitos': [66], "Crédito": 48},
        71: {'Nome': 'TCC1', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Co-Requisitos': [28], 'Semestre': 7, "Crédito": 140, 'Semestre Minimo': 5},
        72: {'Nome': 'TCC2', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos':[71], 'Semestre': 8, "Crédito": 210},
    }

    # For para analisar quais matérias já foram cursadas 
    for materia in grafoCCO.values():
        if materia['Nome'] in materias_cursadas.values():
            materia['Status'] = 'Cursada'

    return grafoCCO
