def define_materias_cursadas(materias_cursadas = {}):
    grafoSIN = {
        0: {'Nome': 'Fundamentos da Programação', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 1, 'Crédito': 64},
        1: {'Nome': 'Programação Orientada a Objetos', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [0], 'Semestre': 2, 'Crédito': 64},
        2: {'Nome': 'Programação Web', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [1], 'Semestre': 3, 'Crédito': 64},
        3: {'Nome': 'Engenharia de Software I', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 2, 'Crédito': 64},
        4: {'Nome': 'Engenharia de Software II', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [3], 'Semestre': 3, 'Crédito': 64},
        5: {'Nome': 'Gerência de Projetos de Software', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [4], 'Semestre': 6, 'Crédito': 64},
        6: {'Nome': 'Desenvolvimento de Sistemas Web', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [2,3,7], 'Semestre': 7, 'Crédito': 64},
        7: {'Nome': 'Banco de Dados I', 'Status': 'Pendente', 'Área de atuação': 'Persistência e Análise Dados', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [15], 'Semestre': 4, 'Crédito': 64},
        8: {'Nome': 'Banco de Dados II', 'Status': 'Pendente', 'Área de atuação': 'Persistência e Análise Dados', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [8], 'Semestre': 5, 'Crédito': 64},
        9: {'Nome': 'Introdução à Análise de Dados', 'Status': 'Pendente', 'Área de atuação': 'Persistência e Análise Dados', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [18], 'Semestre': 5, 'Crédito': 64},
        10: {'Nome': 'Inteligência Artificial', 'Status': 'Pendente', 'Área de atuação': 'Metodologias Computacionais e Otimização', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [18], 'Semestre': 6, 'Crédito': 64},
        11: {'Nome': 'Redes de Computadores', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [12], 'Semestre': 5, 'Crédito': 64},
        12: {'Nome': 'Sistemas Operacionais', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [13,14], 'Semestre': 4, 'Crédito': 64},
        13: {'Nome': 'Organização e Arquitetura de Computadores', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 3, 'Crédito': 64},
        14: {'Nome': 'Algoritmos e Programação I', 'Status': 'Pendente', 'Área de atuação': 'Teoria da Computação', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [0], 'Semestre': 2, 'Crédito': 64},
        15: {'Nome': 'Algoritmos e Programação II', 'Status': 'Pendente', 'Área de atuação': 'Teoria da Computação', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [14], 'Semestre': 3, 'Crédito': 64},
        16: {'Nome': 'Cálculo A', 'Status': 'Pendente', 'Área de atuação': 'Matemática da Computação', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 1, 'Crédito': 64},
        17: {'Nome': 'Matemática Discreta', 'Status': 'Pendente', 'Área de atuação': 'Matemática da Computação', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 2, 'Crédito': 64},
        18: {'Nome': 'Métodos Matemáticos para a Análise de Dados', 'Status': 'Pendente', 'Área de atuação': 'Matemática da Computação', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [16,17,14,15], 'Semestre': 4, 'Crédito': 64},
        19: {'Nome': 'Grafos', 'Status': 'Pendente', 'Área de atuação': 'Matemática da Computação', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [15], 'Semestre': 4, 'Crédito': 64},
        20: {'Nome': 'Comportamentos Organizacional I', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 4, 'Crédito': 32,},
        21: {'Nome': 'Economia', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 3, 'Crédito': 48},
        22: {'Nome': 'Empreendedorismo e Inovação', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 1, 'Crédito': 48},
        23: {'Nome': 'Empreendedorismo Tecnológico', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [22], 'Semestre': 8, 'Crédito': 48},
        24: {'Nome': 'Engenharia Econômica', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 6, 'Crédito': 48},
        25: {'Nome': 'Gestão do Conhecimento', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 5, 'Crédito': 48},
        26: {'Nome': 'Gestão e Governança de TI', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [27], 'Semestre': 9, 'Crédito': 64},
        27: {'Nome': 'Administração Aplicada', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Obrigatoria', 'Pré-Requisitos':  [], 'Semestre': 1, 'Crédito': 32},
        28: {'Nome': 'Mapeamento de Processos', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 2, 'Crédito': 32},
        29: {'Nome': 'Computação e Sociedade', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 8, 'Crédito': 64},
        30: {'Nome': 'Interação Humano-Computador', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [2], 'Semestre': 7, 'Crédito': 64},
        31: {'Nome': 'Metodologia Científica', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [72], 'Semestre': 8, 'Crédito': 64},
        32: {'Nome': 'Projeto Integrado', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 1, 'Crédito': 64},
        33: {'Nome': 'Fundamentos de Sistemas da Informação', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 1, 'Crédito': 64},	
        34: {'Nome': 'Arquitetura de Software', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [3], 'Semestre': None, 'Crédito': 64},
        35: {'Nome': 'Padrões de Projeto', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [2,3], 'Semestre': None, 'Crédito': 64},
        36: {'Nome': 'Engenharia de Software Experimental', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [3], 'Semestre': None, 'Crédito': 64},
        37: {'Nome': 'Tópicos em DES I', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [3], 'Semestre': None, 'Crédito': 64},
        38: {'Nome': 'Tópicos em DES II', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [3], 'Semestre': None, 'Crédito': 64},
        39: {'Nome': 'Desenvolvimento de Jogos', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [0], 'Semestre': None, 'Crédito': 64},
        40: {'Nome': 'Desenvolvimento para Dispositivos Móveis', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [2], 'Semestre': None, 'Crédito': 64},
        41: {'Nome': 'Reutilização de Software', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [4,1,35], 'Semestre': None, 'Crédito': 64},
        42: {'Nome': 'Maratona de programação I', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [14], 'Semestre': None, 'Crédito': 48},
        43: {'Nome': 'Maratona de programação II', 'Status': 'Pendente', 'Área de atuação': 'Desenvolvimento e Engenharia de Software', 'Tipo': 'Optativa', 'Pré-Requisitos': [42], 'Semestre': None, 'Crédito': 48},
        44: {'Nome': 'Bancos de Dados NoSQL', 'Status': 'Pendente', 'Área de atuação': 'Persistência e Análise Dados', 'Tipo': 'Optativa', 'Pré-Requisitos': [7], 'Semestre': None, 'Crédito': 64},
        45: {'Nome': 'Análise de Dados Geoespaciais', 'Status': 'Pendente', 'Área de atuação': 'Persistência e Análise Dados', 'Tipo': 'Optativa', 'Pré-Requisitos': [8, 2], 'Semestre': None, 'Crédito': 64},
        46: {'Nome': 'Mineração de Dados', 'Status': 'Pendente', 'Área de atuação': 'Persistência e Análise Dados', 'Tipo': 'Optativa', 'Pré-Requisitos': [9], 'Semestre': None, 'Crédito': 64},
        47: {'Nome': 'Armazém de Dados', 'Status': 'Pendente', 'Área de atuação': 'Persistência e Análise Dados', 'Tipo': 'Optativa', 'Pré-Requisitos': [9], 'Semestre': None, 'Crédito': 64},
        48: {'Nome': 'Tópicos em PAD', 'Status': 'Pendente', 'Área de atuação': 'Persistência e Análise Dados', 'Tipo': 'Optativa', 'Pré-Requisitos': [7,9], 'Semestre': None, 'Crédito': 64},
        49: {'Nome': 'Métodos Exatos', 'Status': 'Pendente', 'Área de atuação': 'Metodologias Computacionais e Otimização', 'Tipo': 'Optativa', 'Pré-Requisitos': [18,19], 'Semestre': None, 'Crédito': 64},
        50: {'Nome': 'Metaheurísticas', 'Status': 'Pendente', 'Área de atuação': 'Metodologias Computacionais e Otimização', 'Tipo': 'Optativa', 'Pré-Requisitos': [18,19], 'Semestre': None, 'Crédito': 64},
        51: {'Nome': 'Tópicos em MCO', 'Status': 'Pendente', 'Área de atuação': 'Metodologias Computacionais e Otimização', 'Tipo': 'Optativa', 'Pré-Requisitos': [18,19], 'Semestre': None, 'Crédito': 64},
        52: {'Nome': 'Sistemas Embarcados', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [12], 'Semestre': None, 'Crédito': 64},
        53: {'Nome': 'Auditoria e Segurança de SI', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [11], 'Semestre': None, 'Crédito': 64},
        54: {'Nome': 'Computação em Nuvem', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [11], 'Semestre': None, 'Crédito': 64},
        55: {'Nome': 'Programação Paralela', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [11], 'Semestre': None, 'Crédito': 64},
        56: {'Nome': 'Sistemas Distribuídos', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [11], 'Semestre': None, 'Crédito': 64},
        57: {'Nome': 'Tópicos em RSC', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [11], 'Semestre': None, 'Crédito': 64},
        58: {'Nome': 'Simulação e Avaliação de Desempenho', 'Status': 'Pendente', 'Área de atuação': 'Redes e Sistemas Computacionais', 'Tipo': 'Optativa', 'Pré-Requisitos': [56], 'Semestre': None, 'Crédito': 32},
        59: {'Nome': 'Economia da Informação', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 64},
        60: {'Nome': 'Tópicos em ADG', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 64},
        61: {'Nome': 'Finanças: Conceitos e Aplicações', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 32},
        62: {'Nome': 'Finanças para Executivos', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 48},
        63: {'Nome': 'Custos Empresariais', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 48},
        64: {'Nome': 'Logística e Gestão da Cadeia de Suprimentos', 'Status': 'Pendente', 'Área de atuação': 'Admnistração e Gestão', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 32},
        65: {'Nome': 'Tópicos em AHC', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 64},
        66: {'Nome': 'Ciências Humanas e Sociais', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 48},
        67: {'Nome': 'Psicologia: As relações Indivíduo-Grupo', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 48},
        68: {'Nome': 'Comportamento Organizacional II', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 32},
        69: {'Nome': 'Gestão de Carreira', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 32},
        70: {'Nome': 'Psicologia Organizacional e do Trabalho', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 32},
        71: {'Nome': 'Ciências, Tecnologias e Organizações', 'Status': 'Pendente', 'Área de atuação': 'Aspectos Humanos em computação', 'Tipo': 'Optativa', 'Pré-Requisitos': [], 'Semestre': None, 'Crédito': 48},
        72: {'Nome': 'TCC1', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [], 'Semestre': 8, 'Crédito': 144, 'Semestre Minimo': 7},
        73: {'Nome': 'TCC2', 'Status': 'Pendente', 'Área de atuação': '', 'Tipo': 'Obrigatoria', 'Pré-Requisitos': [72], 'Semestre': 9, 'Crédito': 216}
    }

    # For para analisar quais matérias já foram cursadas 
    for materia in grafoSIN.values():
        if materia['Nome'] in materias_cursadas.values():
            materia['Status'] = 'Cursada'

    return grafoSIN
